### ISSUE TITLE
Missing Debuginfo-Pool/Debuginfo-Updates/Source-Pool repos for all products

### ISSUE THREAD

**Issue by roolebo** [SUSE/rmt#216]
We're running into an issue where rmt mirrors only `PRODUCT-Pool` and `PRODUCT-Updates` repos. It's possible to fetch source RPMs for `PRODUCT-Updates` if `mirror_src` is set but I'm struggling to find how to mirror`PRODUCT-Debuginfo-Pool`, `PRODUCT-Debuginfo-Updates` and `PRODUCT-Source-Pool` repos for each configured product.

FWIW, I can see the repos I'm looking for in `repositories` table of `rmt` database, so I think it's something within `rmt` that's filtering the repos out and not making mirrors of them.

**Comment by ikapelyukhin** [comment]
Hello, Roman.

Have you enabled mirroring of debuginfo repos? (Are they in the output of `rmt-cli repos list`?)

`rmt-cli product enable` command does not enable mirroring of debuginfo repos, you can enable mirroring of debuginfo repos manually:

1. Find the IDs of the repos you need in the output of `rmt-cli repos list --all | grep -i debuginfo`
2. Enable each debuginfo repo individually with `rmt-cli repo enable REPOID`

`mirror_src` does something different: sources RPM packages have architecture set to `src` (instead of `x86_64` or other architectures), because they do not contain architecture-specific binaries. Older products have `src` packages in Pool and Update repos, while newer products have separate repos for them. Packages with `src` architecture will be skipped during mirroring process if `mirror_src` is disabled.

I believe that generally debuginfo repos contain architecture-specific binaries and should not contain `src` packages.

Hope this helps, Ivan.

**Comment by roolebo** [comment]
@ikapelyukhin alright, `--all` option shows all the repos I was looking for. Thanks so much!

I think the issue can be closed.
