### ISSUE TITLE
missing "non-oss" from openSUSE Leap, missing option to ignore drpm

### ISSUE THREAD

**Issue by bsenf27** [SUSE/rmt#489]
1) Enhancement
You allowing mirroring openSUSE 15.1, but where are no directory "non-oss" (containing some few packages like xv,opera,iozone).

2) During fresh download, all new files containing same date ("today").
   But large xxx-primary.xml.gz contains for each package meaningful entries like this:
    <time file="15569358642 build="15569358648"/>
    <size package="1024" ... />
    <location href="x86_64/test-1-2-3.x86_64.rpm"/>

     Is it possible to modify timestamp of rpm after download ?

3) I don't love and use delta-packages (drpm) for myself.
    Is it possible to add user option "skip/hide/ignore" drpm ? 

Best regards

**Comment by doccaz** [comment]
+1 for the option to ignore drpm. I run a huge (almost 2TB) repository, and I lose quite a few GB to drpm.

**Comment by ikapelyukhin** [comment]
I don't think there's a "nice" way of skipping `.drpm` downloads. Repository metadata file (`repomd.xml`) has a `deltainfo` section which points to `repodata/$SHA256SUM-deltainfo.xml.gz`.

There's no way of removing it from there without breaking repo GPG signature of the repo (`repomd.xml.asc`). So if we leave the metadata alone and simply skip downloading `.drpm` files, `zypper` will still expect them to be there and will try to download them (and most likely die trying because of 404 errors).

So in order for this to work, you'd have to set `download.use_deltarpm = false` in `/etc/zypp/zypp.conf` on **all** your client machines as well. It's set to `true` by default:

```
##
## Whether to consider using a .delta.rpm when downloading a package
##
## Valid values: boolean
## Default value: true
```

**Comment by felixsch** [comment]
Hello all, looking at Ivans comment I think implementing this feature is out of scope right now. I will close this issue for now. If you still interested please reopen the issue to further discuss possible options. Thank you for your feedback.
