### ISSUE TITLE
Make mirroring path configurable

### ISSUE THREAD

**Issue by thutterer** [SUSE/rmt#538]
Currently it is not possible to configure a different directory than `/usr/share/rmt/public/repo` as mirroring path. It's hardcoded here:
https://github.com/SUSE/rmt/blob/b9895aa88c86a6407428f5c1550b5ceb17d10a1b/lib/rmt.rb#L6

This is problematic when a user wants to mirror to another disk mounted under a different directory, or an NFS share. Users have to work around this with symlinks and such.

We should make this directory configurable in `rmt.conf`.

**Comment by ikapelyukhin** [comment]
`/usr/share/rmt/public/repo` is a symlink. It is configurable -- by changing the symlink to point to whatever directory you want it to.

Making it configurable in the code doesn't make sense, because nginx config also has this path hardcoded (static files are served by nginx). It was a common problem in SMT -- people would change the path in SMT config, then forget about changing the apache config and open L3 tickets due to SMT suddenly being broken.

**Comment by lagartoflojo** [comment]
Thanks for the feedback, @ikapelyukhin !
Instead of creating a new feature that can potentially lead to new bugs, maybe what we need is proper documentation that explains what Ivan said?

**Comment by ikapelyukhin** [comment]
I think we even wanted to document it at some point, but I guess it just fell through the cracks.
I would also suggest asking the support engineers to create a TID addressing this specific customer question.

**Comment by lagartoflojo** [comment]
Ok, I'm getting touch with the doc team to get it added :)

**Comment by thutterer** [comment]
Thanks Ivan and Hernán! :potato:
