### ISSUE TITLE
Support Mirroring Custom Repositories

### ISSUE THREAD

**Issue by tmuntaner** [SUSE/rmt#619]
Currently, RMT can only mirror single SCC repositories. For this, it uses the column `scc_id`. By design, custom repositories don't have an `scc_id`, instead they only use the column `id`.

This poses a problem, how do we target custom repositories for mirroring single custom repositories?

Current Commands

```
  rmt-cli mirror all                 # Mirror all enabled repositories
  rmt-cli mirror repository IDs      # Mirror enabled repositories by given targets (SCC IDs or URLs)
  rmt-cli mirror product IDs         # Mirror enabled repositories for a product with given product IDs
```

**Note:**

* We should maintain `rmt-cli mirror repository IDs` usage of `scc_id` for backwards compatibility.

---

**Option 1: By URL** (https://github.com/SUSE/rmt/pull/618)

`rmt-cli repos custom ls` gives the `name`, `id`, and `url`. `url` is a unique index which doesn't behave differently for scc and custom repositories. So let's support mirroring single repositories by `scc_id` and `url`.

Notes:
* We have precedent for this type of approach with products, where you can either use id like `2526` or `sles/15/x86_64`.
* This will make it easier to script mirroring custom repositories across separate RMT instances, because the URL will be the same.

```
$ rmt-cli mirror repository 2526
$ rmt-cli mirror repository https://download.opensuse.org/repositories/systemsmanagement:/SCC:/RMT/openSUSE_Tumbleweed/
$ rmt-cli mirror repository 2526 https://download.opensuse.org/repositories/systemsmanagement:/SCC:/RMT/openSUSE_Tumbleweed/
```

**Option 2: Custom namespace** (https://github.com/SUSE/rmt/pull/495)

Use a separate namespace `rmt-cli mirror custom` for the `repository` command.

```
$ rmt-cli mirror custom all
$ rmt-cli mirror custom repository 2526
```

**Option 3: Separate command** (https://github.com/SUSE/rmt/pull/498)

Separate the custom repositories from `rmt-cli mirror repository` with a new command `rmt-cli mirror customrepository`.

```
$ rmt-cli mirror repository 2526
$ rmt-cli mirror customrepository 2525
or
$ rmt-cli mirror custom-repository 2525
```

**Option 4: Add prefix to custom repository IDs**

Make a clear separation between `scc_id`s and `id`s with a prefix (e.g. `C#{ID}`).

```
$ rmt-cli mirror repository 2526
$ rmt-cli mirror repository C2525
```

**Comment by tmuntaner** [comment]
@ikapelyukhin and @jesusbv We discussed this as a team, but we're still gathering feedback.

Please feel free to add any input here if you want.

**Comment by thutterer** [comment]
The first three approaches seem reasonable. Haven't looked at their implementation, only on the CLI usage, though.

Question: Does `rmt-cli mirror all` also mirror custom ones? Because if yes, then the `rmt-cli mirror custom all` would feel a bit redundant, and snowflakey. Why then no `mirror not-custom all` :wink: ... So maybe avoid implementing a "subset all" command for now?

Do we plan to ever have custom _products_? Because if not, then we could reduce option 2 to `rmt-cli mirror custom 123` where 123 is a custom ID?

Basically then it would become option 3, right? Just with a shorter command to remember. Because that one is really long and would need a dash to read correct: `custom-repository`.

Option 4 looks like introducing an unexpected behaviour, or breaking. As the `custom enable 123` right now doesn't require a `c` and we cannot just break it, hence support it there with and without prefix, or have it all different between `custom` and `mirror` namespaces.

Option 1 is nice, as it avoids the whole id topic altogether, but the URLs as identifiers are just a pain as you always want to copy&paste them, not type them out.

So, first feedback from me would be that described "option 2.5" might be the "nicest" :smiley: 

```
rmt-cli mirror custom 123
```

**Comment by lcaparroz** [comment]
> So, first feedback from me would be that described "option 2.5" might be the "nicest" smiley
> 
> ```
> rmt-cli mirror custom 123
> ```

@thutterer, which ID would RMT use for custom repositories then?

**Comment by tmuntaner** [comment]
@thutterer 

* `rmt-cli mirror all` mirrors both SCC and custom repositories.
* For the question of custom products, I don't think that we've ever put together a plan of how or if it would work. For me, it would be hard to plan around that right now.

Thanks for your feedback!

**Comment by ikapelyukhin** [comment]
Option 4 FTW -- it just needs to be done correctly. There should be only one ID field in `repositories` table. Custom repos need to have a different format compared to SCC repos (e.g., alphanumeric for custom repos). Current schema is confusing (`repositories.id` vs `repositories.scc_id`).

That would instantly kill all the unnecessary copypasta in the code like `rmt-cli repos custom` and `rmt-cli mirror custom`.

Same approach should also be used for custom products if it's ever implemented.

**Comment by tmuntaner** [comment]
In my opinion, I would vote for either option 1 or 4. I want to remove as much confusion as possible between scc and custom repositories.

However, if we go for option 4, I would also love to consider a way to target a custom repository in a less database dependent way. We kept `scc_id` to ensure that the scc repositories would be the same across RMTs, maybe, we should do something similar for custom repositories as well.

**Comment by ikapelyukhin** [comment]
> maybe, we should do something similar for custom repositories as well.

Yep, custom repo URL checksum as ID would work.

**Comment by jmammen** [comment]
For me option 2 is my favorite. The custom namespace seems to be there and we have basically the same workflow as we have for suse repos just in the custom namespace. `rmt-cli repos ls` displays only scc repos where `rmt-cli repos custom ls` displays only custom repos. To follow this scheme it would just be natural for me to also then select the `id` for custom repos or the `scc_id` for suse repos and then `mirror custom repository <id>` or `mirror repository <scc_id>`.

Did you think about the option to always show the `id` instead of the `scc_id` and allow to mirror by `<id>` but still allow to mirror by `scc_id`?

**Comment by tmuntaner** [comment]
@jmammen We show `scc_id` because it remains the same across RMTs. This makes it easier to enable/disable/mirror a repository coming from SCC. Otherwise, the ID would be different on each machine and you would need a script to properly parse the output data to target the same repo.

**Comment by tmuntaner** [comment]
@ikapelyukhin @jmammen @thutterer @ngetahun 

Thanks for your feedback!

@lcaparroz and I talked and we think that we will try option 4 first, however, we will try our best not to introduce any breaking changes. As we still have the `repos custom` namespace, we can assume that `id` is used and we can still support it for those who have the old `id`. In this way, we have some leverage in deprecating `id` without breaking workflows.

If option 4 gives us any issues, we'll try option 1, as it's our next favored option. `url` may be cumbersome, but it provides an easy identifier which can be used on any repository with very little code or additional namespaces/commands.

**Comment by tmuntaner** [comment]
During the planning meeting, @thutterer also had the idea of using `name` as a target. We'll also throw that into our consideration, but we'll need to work through the issue of `name` not being a unique index.

**Comment by tmuntaner** [comment]
@thutterer we can just ignore the unique index and if multiple repos have the same name, then mirror them all. Thoughts?

**Comment by tmuntaner** [comment]
We've starting working on option 4 with PR #630.
